
package murray_final_project;


public class PracticePanel extends javax.swing.JPanel {

      private Die die1;
      private Die die2;
    
    public PracticePanel() {
        initComponents();
        die1 = new Die();
        die2 = new Die();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dieImage1 = new javax.swing.JLabel();
        dieImage2 = new javax.swing.JLabel();
        rollButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();

        dieImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/murray_final_project/dice1.gif"))); // NOI18N

        dieImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/murray_final_project/dice1.gif"))); // NOI18N

        rollButton.setText("Roll");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });

        messageLabel.setText("Place a bet!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(rollButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dieImage1)
                                .addGap(90, 90, 90)
                                .addComponent(dieImage2)))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dieImage2)
                    .addComponent(dieImage1))
                .addGap(56, 56, 56)
                .addComponent(rollButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(messageLabel)
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
        int sum = die1.roll() + die2.roll();
        messageLabel.setText("You rolled a " + sum);
        dieImage1.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/murray_final_project/dice" + die1.getFace() + ".gif"))); // NOI18N

        dieImage2.setIcon(new javax.swing.ImageIcon(getClass().
                getResource("/murray_final_project/dice" + die2.getFace() + ".gif"))); // NOI18N
    }//GEN-LAST:event_rollButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dieImage1;
    private javax.swing.JLabel dieImage2;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JButton rollButton;
    // End of variables declaration//GEN-END:variables
}
